# Generated by Django 4.1 on 2024-04-13 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odysseyoutbound', '0003_alter_city_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='price',
            field=models.CharField(max_length=100),
        ),
    ]
