# Generated by Django 4.1 on 2024-04-13 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odysseyoutbound', '0004_alter_package_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='image',
            field=models.TextField(default=12),
            preserve_default=False,
        ),
    ]
