# Generated by Django 4.1 on 2024-04-13 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odysseyoutbound', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='cities')),
            ],
        ),
        migrations.AddField(
            model_name='destination',
            name='cities',
            field=models.ManyToManyField(to='odysseyoutbound.city'),
        ),
    ]
